[project]
name = "padatasets"
dynamic = ["version"]
description = "Datasets for protein structure prediction and analysis"
readme = "README.md"
authors = [
    { name = "Ilia Bushmakin", email = "im.bushmakin@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "padata",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.uv.sources]
padata = { workspace = true }

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.hatch.version]
source = "uv-dynamic-versioning"
