[project]
name = "biocontacts"
dynamic = ["version"]
description = "Tool for working with molecular interactions."
authors = [
    {name = "Ilia Bushmakin", email = "im.bushmakin@gmail.com"},
]
dependencies = [
    "padata",
    "scipy<=2.0.0",
]
requires-python = ">3.12.1"
readme = "README.md"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.hatch.version]
source = "uv-dynamic-versioning"
