[project]
name = "osif"
version = "0.1.0"
description = "OSIF: Old Simple models for Inverse Foldings"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.5.2",
    "omegaconf>=2.3.0",
    "pandas>=2.3.1",
    "torch-geometric>=2.6.1",
    "wandb>=0.21.0",
    "prody"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
