[project]
name = "osif"
dynamic = ["version"]
description = "OSIF: Old Simple models for Inverse Foldings"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning>=2.5.2",
    "omegaconf>=2.3.0",
    "pandas>=2.3.1",
    "torch-geometric>=2.6.1",
    "wandb>=0.21.0",
    "prody"
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.hatch.version]
source = "uv-dynamic-versioning"
